Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -16,9 +16,22 @@ jobs:
 
       - name: Fetch README.md content
         run: |
+          # 下载 README.md 文件
           curl -o README.md https://raw.githubusercontent.com/abshare/abshare.github.io/refs/heads/main/README.md
-          LINK=$(grep -A 1 ">🚀免费Clash订阅链接" README.md | tail -n 1 | sed 's/^https:/https:\/\//')
           
+          # 输出文件内容以调试
+          echo "Content of README.md:"
+          cat README.md
+          
+          # 提取链接
+          LINK=$(grep -A 1 ">🚀免费Clash订阅链接" README.md | tail -n 1 | sed 's/^https:/https:\/\//')
+
+          # 检查链接是否为空
+          if [ -z "$LINK" ]; then
+            echo "Failed to find the download link."
+            exit 1
+          fi
+
           echo "Download link is: $LINK"
           
           # 下载链接内容
